spring.application.name=catalog

# 1. Conexiunea la baza de date MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/parfumerie_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Spring Mail Configuration (Necessary for sending email)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexdragulescu0801@gmail.com
spring.mail.password=jvytrjrguohfrhyp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 2. Configura?ii JPA ?i Hibernate
# 'update' va crea tabelele dac? nu exist?, bazat pe clasele Entity
spring.jpa.hibernate.ddl-auto=none
# Afi?eaz? interog?rile SQL generate de Hibernate în consol?
spring.jpa.show-sql=true

# 3. Importarea Datelor Ini?iale (Utilizatori ?i Parfumuri)
# Aceast? linie indic? Spring s? execute fi?ierul data.sql la pornire
spring.sql.init.mode=always

# Dezactiveaza functia de initializare a bazei de date a lui Hibernate
# (care poate interfera cu executia data.sql in unele versiuni)
spring.jpa.defer-datasource-initialization=true

# 3. Specific? numele fi?ierelor (op?ional, dar clarific?)
# Acestea vor rula in ordinea schema, apoi data
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:date.sql